# Generated by Django 6.0.3 on 2026-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0002_rename_price_per_hour_expertisepost_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertisepost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/'),
        ),
    ]
