# Generated by Django 6.0.3 on 2026-05-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0003_expertisepost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertisepost',
            name='total_sessions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SessionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_slots', to='turo_api.expertisepost')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('post', 'date', 'start_time')},
            },
        ),
    ]
