# Generated by Django 6.0.3 on 2026-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0004_expertisepost_total_sessions_sessionslot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionslot',
            options={'ordering': ['session_number', 'date', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='sessionslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sessionslot',
            name='session_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='sessionslot',
            unique_together={('post', 'session_number')},
        ),
    ]
