# Generated by Django 6.0.3 on 2026-05-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0005_alter_sessionslot_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionslot',
            unique_together={('post', 'session_number', 'date', 'start_time')},
        ),
    ]
