# Generated by Django 6.0.3 on 2026-05-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0006_alter_sessionslot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='session_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='turo_api.sessionslot'),
        ),
    ]
