# Generated by Django 6.0.3 on 2026-05-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0008_add_location_to_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='barangay',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='municipality',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
