# Generated by Django 6.0.3 on 2026-05-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0010_profile_address_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
