# Generated by Django 6.0.3 on 2026-05-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0011_remove_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('visa', 'Visa/Credit Card'), ('cash', 'Cash')], default='gcash', max_length=20),
        ),
    ]
