# Generated by Django 6.0.3 on 2026-05-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0012_payment_notes_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True),
        ),
    ]
