# Generated by Django 6.0.3 on 2026-05-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0013_profile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tutor_tier',
            field=models.CharField(choices=[('basic', 'Tier 1 - Basic Tutor'), ('plus', 'Tier 2 - Plus Tutor'), ('pro', 'Tier 3 - Pro Tutor')], default='basic', max_length=20),
        ),
    ]
