# Generated by Django 6.0.3 on 2026-05-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0014_profile_tutor_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='achievement_proof',
            field=models.FileField(blank=True, null=True, upload_to='achievement_proofs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='credentials_file',
            field=models.FileField(blank=True, null=True, upload_to='credentials/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tier_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tier_review_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
    ]
