# Generated by Django 6.0.3 on 2026-05-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0015_profile_achievement_proof_profile_credentials_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievement_proof',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='credentials_file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tier_review_note',
        ),
        migrations.AddField(
            model_name='profile',
            name='credentials_document',
            field=models.FileField(blank=True, null=True, upload_to='tutor_credentials/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tier_review_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tier_review_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
    ]
