# Generated by Django 6.0.3 on 2026-05-15 12:40

from django.db import migrations, models


def set_existing_profiles_id_verified(apps, schema_editor):
    Profile = apps.get_model('turo_api', 'Profile')
    Profile.objects.update(requires_id_verification=False)

class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0018_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='requires_id_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_existing_profiles_id_verified),
    ]
