# Generated by Django 6.0.3 on 2026-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0020_profile_id_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='gcash_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
