# Generated by Django 6.0.3 on 2026-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0021_profile_billing_name_profile_gcash_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='guardian_id_photos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'Philippine National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('philhealth', 'PhilHealth ID'), ('sss', 'SSS ID'), ('postal', 'Postal ID'), ('voters', "Voter's ID"), ('school_id', 'School ID'), ('other', 'Other Government ID')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'Philippine National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('philhealth', 'PhilHealth ID'), ('sss', 'SSS ID'), ('postal', 'Postal ID'), ('voters', "Voter's ID"), ('school_id', 'School ID'), ('other', 'Other Government ID')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_minor',
            field=models.BooleanField(default=False),
        ),
    ]
