# Generated by Django 6.0.3 on 2026-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turo_api', '0022_profile_birthday_profile_guardian_id_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='guardian_relationship',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_minor',
        ),
        migrations.AlterField(
            model_name='profile',
            name='guardian_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='guardian_ids/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guardian_id_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
